### ISSUE TITLE
Error in ullekhanam schema link

### ISSUE THREAD

**Issue by drdhaval2785** [vedavaapi/vedavaapi_py_api#3]
https://api.vedavaapi.org/py/ullekhanam/v1/schemas

builtins.TypeError
TypeError: get() got an unexpected keyword argument 'headers'

**Comment by vvasuki** [comment]
Seems to be fine:

![image](https://user-images.githubusercontent.com/2664797/35779011-60399788-097b-11e8-8174-e9102ebf1232.png)

**Comment by drdhaval2785** [comment]
```
builtins.TypeError
TypeError: get() got an unexpected keyword argument 'headers'

Traceback (most recent call last)
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 557, in error_router
return original_handler(e)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 557, in error_router
return original_handler(e)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 557, in error_router
return original_handler(e)
File "/usr/local/lib/python3.6/dist-packages/Flask_Cors-3.0.3-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 557, in error_router
return original_handler(e)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 557, in error_router
return original_handler(e)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 557, in error_router
return original_handler(e)
File "/usr/local/lib/python3.6/dist-packages/Flask_Cors-3.0.3-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 317, in wrapper
return self.make_response(data, code, headers=headers)
File "/usr/local/lib/python3.6/dist-packages/flask_restplus-0.10.1-py3.6.egg/flask_restplus/api.py", line 338, in make_response
resp = self.representations[mediatype](data, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'headers'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by vvasuki** [comment]
How would I reproduce this? You're trying to run this as a wsgi plugin in your apache server?

**Comment by vvasuki** [comment]
Was able to reproduce in chrome, will investigate - 
![image](https://user-images.githubusercontent.com/2664797/35782602-2a7900d2-09af-11e8-85d7-6d44a25b473d.png)

**Comment by drdhaval2785** [comment]
Yes. My error was also on Chrome.

**Comment by vvasuki** [comment]
This is mysterious. Firefox vs Chrome header comparison [here](https://www.diffchecker.com/sIOZEpKx) does not reveal any significant difference.
``` 
curl -X GET --header 'Accept: application/json' 'https://api.vedavaapi.org/py/ullekhanam/v1/schemas' 
``` 

works fine as well. I will remove the direct link to https://api.vedavaapi.org/py/ullekhanam/v1/schemas in the docs; and escalate this bug upstream.

**Comment by vvasuki** [comment]
Another weird thing is that https://api.vedavaapi.org/py/auth/v1/schemas works fine on Chrome.
